In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [24]:
a2 = np.array([[1, 2., 3.3],
              [4, 5., 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
a2.shape

(2, 3)

In [26]:
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17 ,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a3.shape

(2, 3, 3)

In [28]:
a3[:, 0, :]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [29]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [30]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [31]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [32]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Numpy arrays

In [35]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [37]:
sample_array.dtype

dtype('int32')

In [39]:
ones = np.ones((2, 3))

In [40]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
ones.dtype

dtype('float64')

In [42]:
type(ones)

numpy.ndarray

In [44]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [49]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 1, 8, 7, 8],
       [8, 8, 7, 0, 5],
       [6, 3, 5, 4, 3]])

In [50]:
random_array.size

15

In [51]:
random_array.shape

(3, 5)

In [57]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.84389622, 0.97804394, 0.30090225],
       [0.78051267, 0.46294016, 0.41536464],
       [0.64826772, 0.87865665, 0.20840742],
       [0.34842411, 0.99196715, 0.4434658 ],
       [0.04451144, 0.09393663, 0.8359632 ]])

In [61]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.68945754, 0.45688058, 0.13172015],
       [0.81782011, 0.06836681, 0.929062  ],
       [0.91392473, 0.60424012, 0.03476149],
       [0.38677291, 0.92385808, 0.43099197],
       [0.86809314, 0.22923095, 0.85520222]])

In [83]:
# Pseudo-random numbers
# np.random.seed
np.random.seed(seed = 3)
random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

## 3. Viewing arrays and matrices

In [85]:
np.unique(random_array_4)

array([0, 3, 4, 5, 6, 7, 8, 9])

In [86]:
random_array_4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

In [87]:
a1

array([1, 2, 3])

In [88]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [89]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a1[0]

1

In [91]:
a2[0]

array([1. , 2. , 3.3])

In [92]:
a2[0, :]

array([1. , 2. , 3.3])

In [93]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
a3.shape

(2, 3, 3)

In [96]:
a3[0, :, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
a3[0:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [98]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [99]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))

In [100]:
a4

array([[[[7, 8, 1, 6, 2],
         [2, 1, 3, 5, 8],
         [1, 8, 7, 8, 1],
         [0, 5, 4, 1, 5]],

        [[4, 7, 6, 0, 0],
         [9, 2, 4, 5, 8],
         [8, 7, 5, 1, 1],
         [1, 5, 5, 7, 4]],

        [[3, 0, 0, 0, 0],
         [2, 2, 7, 0, 5],
         [0, 1, 4, 1, 2],
         [2, 4, 8, 0, 6]]],


       [[[0, 4, 1, 5, 1],
         [8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7],
         [4, 0, 0, 4, 3]],

        [[0, 8, 2, 7, 2],
         [1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4],
         [1, 6, 7, 9, 1]],

        [[0, 0, 5, 8, 4],
         [8, 8, 3, 4, 9],
         [2, 5, 4, 7, 9],
         [1, 9, 0, 7, 4]]]])

In [102]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [106]:
#  Get the first 3 phone of the inner most array


In [105]:
a4[:, :, :, :3]

array([[[[7, 8, 1],
         [2, 1, 3],
         [1, 8, 7],
         [0, 5, 4]],

        [[4, 7, 6],
         [9, 2, 4],
         [8, 7, 5],
         [1, 5, 5]],

        [[3, 0, 0],
         [2, 2, 7],
         [0, 1, 4],
         [2, 4, 8]]],


       [[[0, 4, 1],
         [8, 8, 7],
         [9, 1, 7],
         [4, 0, 0]],

        [[0, 8, 2],
         [1, 3, 2],
         [2, 2, 7],
         [1, 6, 7]],

        [[0, 0, 5],
         [8, 8, 3],
         [2, 5, 4],
         [1, 9, 0]]]])