In [1]:
import numpy as np

## DataType and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 3, 4])
a1

array([1, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.size

3

In [7]:
a2 = np.array([[2, 3, 4], [3, 5, 6]])
a2

array([[2, 3, 4],
       [3, 5, 6]])

In [11]:
type(a2)

numpy.ndarray

In [13]:
a2.shape

(2, 3)

In [17]:
a3 = np.array([[[3, 4, 5],
              [4, 6, 7],
              [4, 6, 8]],
             [[11, 12, 13],
             [14, 15, 16],
             [17, 18, 19]]])

In [18]:
a3

array([[[ 3,  4,  5],
        [ 4,  6,  7],
        [ 4,  6,  8]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [19]:
type(a3)

numpy.ndarray

In [20]:
a3.shape

(2, 3, 3)

In [21]:
a3.ndim

3

In [25]:
# Create a DataFrame form a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  2  3  4
1  3  5  6

## 2. Creating a Numpy array

In [26]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ones.dtype

dtype('float64')

In [35]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [41]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 5, 8, 9, 4],
       [3, 9, 5, 4, 2],
       [3, 8, 4, 3, 0]])

In [42]:
random_array.size

15

In [43]:
random_array.shape

(3, 5)

In [49]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.89678395, 0.35466674, 0.38002426],
       [0.52042334, 0.04166865, 0.23995247],
       [0.26172566, 0.98040537, 0.13651662],
       [0.96886689, 0.38697226, 0.31289344],
       [0.49896855, 0.92291586, 0.48905725]])

In [57]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.97456333, 0.30626647, 0.43511174],
       [0.40878304, 0.96397787, 0.62002529],
       [0.79859097, 0.26560758, 0.92284858],
       [0.91857257, 0.44137113, 0.55778615],
       [0.17367476, 0.36206119, 0.84270848]])

In [65]:
# Sudo random numbers
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [66]:
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## 3. Viewing arrays nd matrices

In [67]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [68]:
a1

array([1, 3, 4])

In [69]:
a2

array([[2, 3, 4],
       [3, 5, 6]])

In [70]:
a3

array([[[ 3,  4,  5],
        [ 4,  6,  7],
        [ 4,  6,  8]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [71]:
a1[0]

1

In [72]:
a2[0]

array([2, 3, 4])

In [73]:
a2.shape

(2, 3)

In [75]:
a3

array([[[ 3,  4,  5],
        [ 4,  6,  7],
        [ 4,  6,  8]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [76]:
a3[0]

array([[3, 4, 5],
       [4, 6, 7],
       [4, 6, 8]])

In [80]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 2, 0, 3, 4],
         [6, 0, 2, 1, 8],
         [9, 5, 9, 2, 7],
         [7, 1, 5, 6, 1]],

        [[9, 1, 9, 0, 7],
         [0, 8, 5, 6, 9],
         [6, 9, 2, 1, 8],
         [7, 9, 6, 8, 3]],

        [[3, 0, 7, 2, 6],
         [1, 1, 6, 5, 2],
         [8, 9, 5, 9, 9],
         [5, 0, 3, 9, 5]]],


       [[[5, 4, 0, 7, 4],
         [4, 6, 3, 5, 3],
         [2, 6, 7, 3, 1],
         [9, 2, 0, 7, 2]],

        [[9, 6, 9, 4, 9],
         [4, 6, 8, 4, 0],
         [9, 9, 0, 1, 5],
         [8, 7, 4, 0, 6]],

        [[4, 5, 6, 2, 9],
         [2, 4, 5, 8, 4],
         [0, 3, 4, 9, 9],
         [4, 6, 3, 0, 4]]]])

In [78]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [87]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[4, 2, 0, 3],
         [6, 0, 2, 1],
         [9, 5, 9, 2],
         [7, 1, 5, 6]],

        [[9, 1, 9, 0],
         [0, 8, 5, 6],
         [6, 9, 2, 1],
         [7, 9, 6, 8]],

        [[3, 0, 7, 2],
         [1, 1, 6, 5],
         [8, 9, 5, 9],
         [5, 0, 3, 9]]],


       [[[5, 4, 0, 7],
         [4, 6, 3, 5],
         [2, 6, 7, 3],
         [9, 2, 0, 7]],

        [[9, 6, 9, 4],
         [4, 6, 8, 4],
         [9, 9, 0, 1],
         [8, 7, 4, 0]],

        [[4, 5, 6, 2],
         [2, 4, 5, 8],
         [0, 3, 4, 9],
         [4, 6, 3, 0]]]])

## 4. Manupulating $ comparing arrays

### Arithmetic

## Aggregation

In [92]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

1000000000

In [93]:
massive_array[:10]

array([0.15584021, 0.87904216, 0.00109076, 0.50964085, 0.52271788,
       0.72682508, 0.75602187, 0.23166883, 0.88202755, 0.17911201])

In [ ]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy's sum()

Use NumPy methods on NumPy arrays (`np.sum()`), and Use Pythons methods `sum()` pm Python datatypes.